# Generated by Django 2.1 on 2018-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='src',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
