# Generated by Django 2.1 on 2018-08-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='data',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
