# Generated by Django 2.1 on 2018-08-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmstatus', '0002_status_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('OFF', 'Offline'), ('CON', 'Connectiong'), ('ON', 'Online'), ('RING', 'Ringing')], max_length=100)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=256)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='StatusLookup',
        ),
    ]
