# Generated by Django 2.1 on 2018-08-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmstatus', '0003_auto_20180822_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('OFF', 'Offline'), ('CON', 'Connecting'), ('ON', 'Online'), ('RING', 'Ringing')], max_length=100),
        ),
    ]
