# Generated by Django 2.1 on 2018-08-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarmstatus', '0004_auto_20180822_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmrequests',
            name='source',
        ),
    ]
