# Generated by Django 2.1 on 2018-08-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmstatus', '0005_remove_alarmrequests_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('OFF', 'Offline'), ('CON', 'Connecting'), ('ON', 'Online'), ('RING', 'Ringing'), ('PRO', 'Processing'), ('UP', 'Uploading')], max_length=100),
        ),
    ]
