# Generated by Django 2.1 on 2018-09-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmstatus', '0006_auto_20180828_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('OFF', 'Offline'), ('CON', 'Connecting'), ('ON', 'Online'), ('RIN', 'Ringing'), ('PRO', 'Processing'), ('UP', 'Uploading')], max_length=100),
        ),
    ]
